# Generated by Django 5.0.6 on 2024-07-07 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Escolha de 1 à 5 estrelas.'), django.core.validators.MaxValueValidator(5, 'Escolha de 1 à 5 estrelas.')]),
        ),
    ]
