# Generated by Django 5.0.6 on 2024-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_birthday_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('CA', 'Canadá'), ('BR', 'Brasil'), ('UK', 'Reino Unido')], max_length=100, null=True),
        ),
    ]
